#!/bin/bash

cd `dirname $0`
name=`basename $(pwd)`

branch=`git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,'`
tag=`git describe --tags --abbrev=0 2> /dev/null`
hash=`git rev-parse --short HEAD`

if [ -n "$tag" ]; then
    package_version=$tag
    display_version=$tag
else
    package_version=$hash
    display_version=$hash
fi

# update version in plugin manifest
current_version=`grep -P "Version: .*$" transmission.php | awk '{ print $2 }'`
sed -Ei "s|(Version: ).*$|\1$display_version|" ./transmission.php

dest="builds/$name-$package_version.zip"
rm -f $dest*

composer install --no-ansi --no-dev --no-interaction --optimize-autoloader

# build assets
yarn install --production=false
node_modules/gulp/bin/gulp.js --env=prod

# not needed since no js dependencies for production
# so simply exclude node_modules from tar archive
#yarn install --production=true

if [ ! -d "builds" ]; then
    mkdir "builds"
fi

cd ..
zip \
    -x \
        $name/.git/\* \
        $name/.gitignore \
        $name/.rsync-exclude \
        $name/assets/src/\* \
        $name/build \
        $name/builds/\* \
        $name/composer.json \
        $name/composer.lock \
        $name/gulpfile.js \
        $name/node_modules/\* \
        $name/package.json \
        $name/yarn.lock \
    -r $name/$dest \
    ./$name

cd $name

# restore current version in transmission.php
sed -Ei "s|(Version: ).*$|\1$current_version|" ./transmission.php